import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/Navbar'
import { PizzaList } from "../components/pizzaList"
import axios from "axios"

const Home = ({pizzaList}:{pizzaList:[]}) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-12 min-h-screen pt-4">
          <PizzaList pizzaList={pizzaList} />
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps = async() => {
  const res = await axios.get("http://localhost:3000/api/products")
  return {
    props: {
      pizzaList: res.data
    }
  }
}