import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/Navbar'
import { ItemCard } from "../components/ItemCard"

const Home: NextPage = () => {
  const products = [
    {
      id: 1,
      title: "title satu",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus nulla arcu. Maecenas eget hendrerit sem. Sed eu rhoncus lacus, malesuada vulputate dolor."
    },
    {
      id: 2,
      title: "title dua",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus nulla arcu. Maecenas eget hendrerit sem. Sed eu rhoncus lacus, malesuada vulputate dolor."
    },
    {
      id: 3,
      title: "title tiga",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus nulla arcu. Maecenas eget hendrerit sem. Sed eu rhoncus lacus, malesuada vulputate dolor."
    },
    {
      id: 4,
      title: "title empat",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris cursus nulla arcu. Maecenas eget hendrerit sem. Sed eu rhoncus lacus, malesuada vulputate dolor."
    }
  ]
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar/> */}
      <main className="px-12 min-h-screen pt-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 text-center">
          {products.map((item:{id:number, title:string, description:string}) => {
            return <ItemCard key={item.id} item={item}/>
          })}
        </div>
      </main>
    </div>
  )
}

export default Home
